name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]
        target: [Nemesis_App, Nemesis_Core_Engine, Nemesis_Havok]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup Qt
        uses: ./.github/actions/setup-qt

      - name: Build and Upload Artifact
        uses: ./.github/actions/build-common
        with:
          target: ${{ matrix.target }}
          mode: release
          runtimes: ${{ matrix.target == 'Nemesis_Havok' && 'MT' || '' }}
          artifact_name: ${{ matrix.target }}-${{ matrix.os }}
