name: XMake build

on:
  push:
    branches: ["ci"]
  pull_request:
    branches: ["ci"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          dir: "${{ github.workspace}}/"
          cache: true

      - name: Python Cache
        uses: actions/cache@v3
        with:
          path: |
            ./Python3_10_11_x64-windows
          key: Python3-${{ runner.os }}
      - name: Get Python3.8.10
        shell: pwsh
        run: |
          if (!$(Test-Path ./Python3_10_11_x64-windows)) {
            Invoke-WebRequest https://github.com/SARDONYX-forks/Project-New-Reign---Nemesis-Main/releases/download/v0.84-beta/Python3_10_11_x64-windows.zip -OutFile "./Python3_10_11_x64-windows.zip"
            Expand-Archive ./Python3_10_11_x64-windows.zip
          }

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build Nemesis
        run: xmake --yes
        continue-on-error: true # Add because cache is wasted while build fails

      - name: Show file tree
        shell: pwsh
        run: mkdir -p ./build;tree /f > ./build/tree.txt

      - name: Compress build files
        shell: pwsh
        run: Compress-Archive ./Build ./build.zip

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          path: ${{ github.workspace}}/build.zip
